spring:
  datasource:
    url: jdbc:mysql://www.chenqi.club:3306/user_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: cq218zz@163.com
    password: WLNAWORHEDUDACAM
    default-encoding: utf-8
    properties:
      mail:
        debug: true
  application:
    name: user-server
  cloud:
    nacos:
      server-addr: 101.35.107.110:8848 # nacos地址

user-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080