spring:
  datasource:
    url: jdbc:mysql://www.chenqi.club:3306/?user_server=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: cq218zz@163.com
    password: WLNAWORHEDUDACAM
    default-encoding: utf-8
    properties:
      mail:
        debug: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080