spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: 101.35.107.110:8848 # nacos地址
    gateway:
      routes:
        - id: userserver
          uri: lb://user-server
          predicates:
            - Path=/user/**
server:
  port: 80